export const AGVC_CONTROL = {
  agc: [
    {
      name: "有功控制退出",
      value: 0,
      valKey: "ActivePowerControlModeFeedback",
      controlKey: "ActivePowerControlMode",
      controlType: 25,
      controlPointName: "AGC有功控制",
    },
    {
      name: "有功本地控制",
      value: 1,
      valKey: "ActivePowerControlModeFeedback",
      controlKey: "ActivePowerControlMode",
      key: "LocalActivePowerSetFeedback",
      controlType: 26,
      controlPointName: "AGC有功控制",
    },
    {
      name: "有功AGC控制",
      value: 2,
      valKey: "ActivePowerControlModeFeedback",
      controlKey: "ActivePowerControlMode",
      key: "AGCActivePowerSetFeedback",
      controlType: 27,
      controlPointName: "AGC有功控制",
    },
    {
      name: "有功集控控制",
      value: 3,
      valKey: "ActivePowerControlModeFeedback",
      controlKey: "ActivePowerControlMode",
      key: "CenterActivePowerSetFeedback",
      controlType: 28,
      controlPointName: "AGC有功控制",
    },
  ],
  avc: [
    {
      name: "无功控制退出",
      value: 0,
      valKey: "ReactivePowerControlModeFeedback",
      controlKey: "ReactivePowerControlMode",
      controlType: 29,
      controlPointName: "AVC无功控制",
    },
    {
      name: "无功本地控制",
      value: 1,
      valKey: "ReactivePowerControlModeFeedback",
      controlKey: "ReactivePowerControlMode",
      key: "LocalReactivePowerSetFeedback",
      controlType: 30,
      controlPointName: "AVC无功控制",
    },
    {
      name: "无功AVC控制",
      value: 2,
      valKey: "ReactivePowerControlModeFeedback",
      controlKey: "ReactivePowerControlMode",
      key: "AVCReactivePowerSetFeedback",
      controlType: 31,
      controlPointName: "AVC无功控制",
    },
    {
      name: "无功集控控制",
      value: 3,
      valKey: "ReactivePowerControlModeFeedback",
      controlKey: "ReactivePowerControlMode",
      key: "CenterReactivePowerSetFeedback",
      controlType: 32,
      controlPointName: "AVC无功控制",
    },
  ],
}
