export const CONVERT_KEY = [
  {
    includesPoint: [
      "THXF_Other_Ra_F32_3",
      "THXF_Other_Ra_F32_4",
      "THXF_Other_Ra_F32_5",
      "THXF_Other_Ra_F32_6",
      "THXF_Other_Ra_F32_7",
      "THXF_Other_Ra_F32_8",
      "THXF_Other_Ra_F32_9",
      "THXF_Other_Ra_F32_10",
      "THXF_Other_Ra_F32_11",
      "THXF_Other_Ra_F32_12",
      "THXF_Other_Ra_F32_13",
      "THXF_Other_Ra_F32_14",
      "THXF_Other_Ra_F32_15",
      "THXF_Other_Ra_F32_16",
      "THXF_Other_Ra_F32_17",
      "THXF_Other_Ra_F32_18",
      "THXF_Other_Ra_F32_19",
      "THXF_Other_Ra_F32_20",
      "THXF_Other_Ra_F32_21",
      "THXF_Other_Ra_F32_22",
      "THXF_Other_Ra_F32_23",
      "THXF_Other_Ra_F32_24",
      "THXF_Other_Ra_F32_27",
      "THXF_Other_Ra_F32_28",
      "THXF_Other_Ra_F32_29",
      "THXF_Other_Ra_F32_30",
      "THXF_Other_Ra_F32_31",
      "THXF_Other_Ra_F32_32",
    ],
    keyValueMap: {
      0: "--",
      1: "火警",
      10: "回路短路",
      11: "断电",
      12: "重码",
      13: "正常",
      14: "模块复位",
      15: "反馈清除",
      16: "探测器屏蔽",
      17: "探测器启用",
      18: "主电故障清除",
      19: "备电故障清除",
      2: "联动",
      3: "反馈",
      4: "离线",
      5: "类型错误",
      6: "短路",
      7: "开路",
      8: "主电故障",
      9: "备电故障",
    },
  },
  {
    includesPoint: ["THXF_Other_Ra_F32_1"],
    keyValueMap: {
      0: "无故障",
      1: "火警",
      2: "联动",
      3: "反馈",
    },
  },
  {
    includesPoint: ["THXF_Other_Ra_F32_2"],
    keyValueMap: {
      0: "无警告",
      10: "回路短路",
      11: "断电",
      12: "重码",
      4: "离线",
      5: "类型错误",
      6: "短路",
      7: "开路",
      8: "主电故障",
      9: "备电故障",
    },
  },
]
