export const STATE_TYPE = [
  {
    id: 1,
    state: "1",
    stateDesc: "正常发电",
    color: "#34c537",
    stateType: "MAIN",
    deviceType: "WT",
    parentId: null,
    styleInfo: {
      color: "#34c537",
    },
  },
  {
    id: 2,
    state: "1",
    stateDesc: "正常发电",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 1,
  },
  //
  {
    id: 3,
    state: "2",
    stateDesc: "限功率",
    color: "#b73cf2",
    stateType: "MAIN",
    deviceType: "WT",
    parentId: 1,
    styleInfo: {
      color: "#b73cf2",
    },
  },
  {
    id: 4,
    state: "2",
    stateDesc: "电网限功率",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 3,
  },
  {
    id: 5,
    state: "3",
    stateDesc: "主控限功率",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 3,
  },
  {
    id: 6,
    state: "4",
    stateDesc: "手动限功率",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 3,
  },
  {
    id: 7,
    state: "5",
    stateDesc: "结冰限功率",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 3,
  },
  {
    id: 8,
    state: "3",
    stateDesc: "待机",
    color: "#53d4f8",
    stateType: "MAIN",
    deviceType: "WT",
    parentId: 8,
    styleInfo: {
      color: "#53d4f8",
    },
  },
  {
    id: 9,
    state: "6",
    stateDesc: "小风待机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 8,
  },
  {
    id: 10,
    state: "7",
    stateDesc: "大风切出",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 8,
  },
  {
    id: 11,
    state: "8",
    stateDesc: "温度低待机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 8,
  },
  {
    id: 12,
    state: "9",
    stateDesc: "温度高待机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 8,
  },
  {
    id: 13,
    state: "10",
    stateDesc: "技术性待机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 8,
  },
  {
    id: 14,
    state: "11",
    stateDesc: "异常待机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 8,
  },
  //维护
  {
    id: 15,
    state: "4",
    stateDesc: "维护",
    color: "#ef189d",
    stateType: "MAIN",
    deviceType: "WT",
    parentId: null,
    styleInfo: {
      color: "#ef189d",
    },
  },
  {
    id: 16,
    state: "12",
    stateDesc: "检测维护",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 15,
  },
  {
    id: 17,
    state: "13",
    stateDesc: "定检维护",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 15,
  },
  {
    id: 18,
    state: "14",
    stateDesc: "巡检维护",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 15,
  },
  {
    id: 19,
    state: "15",
    stateDesc: "缺陷维护",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 15,
  },
  {
    id: 20,
    state: "16",
    stateDesc: "技改维护",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 15,
  },
  {
    id: 21,
    state: "17",
    stateDesc: "预警维护",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 15,
  },
  //停机
  {
    id: 22,
    state: "5",
    stateDesc: "停机",
    color: "#f98a12",
    stateType: "MAIN",
    deviceType: "WT",
    parentId: null,
    styleInfo: {
      color: "#f98a12",
    },
  },
  {
    id: 23,
    state: "18",
    stateDesc: "覆冰",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 24,
    state: "19",
    stateDesc: "台风",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 25,
    state: "20",
    stateDesc: "地震",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 26,
    state: "21",
    stateDesc: "民事原因",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 27,
    state: "22",
    stateDesc: "新建风机接入",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 28,
    state: "23",
    stateDesc: "扇区管理停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 29,
    state: "24",
    stateDesc: "电网限功率停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 30,
    state: "25",
    stateDesc: "现货交易停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 31,
    state: "26",
    stateDesc: "其他原因",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 32,
    state: "27",
    stateDesc: "电气检测停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 33,
    state: "28",
    stateDesc: "电气定检停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 34,
    state: "29",
    stateDesc: "电气巡检停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 35,
    state: "30",
    stateDesc: "电气缺陷停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 36,
    state: "31",
    stateDesc: "电气技改停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 37,
    state: "32",
    stateDesc: "电气故障停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 38,
    state: "33",
    stateDesc: "电网故障停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  {
    id: 39,
    state: "34",
    stateDesc: "电网检修停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 22,
  },
  //故障
  {
    id: 40,
    state: "6",
    stateDesc: "故障",
    color: "#f02828",
    stateType: "MAIN",
    deviceType: "WT",
    parentId: null,
    styleInfo: {
      color: "#f02828",
    },
  },
  {
    id: 41,
    state: "35",
    stateDesc: "故障检修",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 40,
  },
  {
    id: 42,
    state: "36",
    stateDesc: "故障停机",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 40,
  },
  //通讯中断
  {
    id: 43,
    state: "7",
    stateDesc: "无通讯",
    color: "#ffffff",
    stateType: "MAIN",
    deviceType: "WT",
    parentId: 1,
    styleInfo: {
      color: "#ffffff",
    },
  },
  {
    id: 44,
    state: "37",
    stateDesc: "无通讯",
    color: "",
    stateType: "SUB",
    deviceType: "WT",
    parentId: 43,
  },

  // 光伏
  {
    id: 45,
    state: "1",
    color: "#34c537",
    stateType: "MAIN",
    deviceType: "PVINV",
    parentId: null,
    stateDesc: "正常发电",
    styleInfo: {
      color: "#34c537",
    },
  },
  { id: 73, state: "1", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 45, stateDesc: "正常发电" },
  {
    id: 74,
    state: "2",
    color: "#b73cf2",
    stateType: "MAIN",
    deviceType: "PVINV",
    parentId: null,
    stateDesc: "限功率",
    styleInfo: {
      color: "#b73cf2",
    },
  },
  { id: 46, state: "2", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 74, stateDesc: "电网限功率" },
  { id: 47, state: "3", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 74, stateDesc: "主控限功率" },
  {
    id: 75,
    state: "3",
    color: "#53d4f8",
    stateType: "MAIN",
    deviceType: "PVINV",
    parentId: null,
    stateDesc: "待机",
    styleInfo: {
      color: "#53d4f8",
    },
  },
  { id: 48, state: "4", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 75, stateDesc: "待机" },
  {
    id: 76,
    state: "4",
    color: "#f98a12",
    stateType: "MAIN",
    deviceType: "PVINV",
    parentId: null,
    stateDesc: "停机",
    styleInfo: {
      color: "#f98a12",
    },
  },
  { id: 49, state: "5", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "检测维护" },
  { id: 50, state: "6", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "定检维护" },
  { id: 51, state: "7", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "缺陷维护" },
  { id: 52, state: "8", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "技改维护" },
  { id: 53, state: "9", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "预警维护" },
  { id: 54, state: "10", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "故障维护" },
  { id: 55, state: "11", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "积雪" },
  { id: 56, state: "12", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "台风" },
  { id: 57, state: "13", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "地震" },
  { id: 58, state: "14", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "民事原因" },
  { id: 59, state: "15", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "新建设备接入" },
  { id: 60, state: "16", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "电网限功率停机" },
  { id: 61, state: "17", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "现货交易停机" },
  { id: 62, state: "18", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "其他原因" },
  { id: 63, state: "19", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "电气检测停机" },
  { id: 64, state: "20", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "电气定检停机" },
  { id: 65, state: "21", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "电气巡检停机" },
  { id: 66, state: "22", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "电气缺陷停机" },
  { id: 67, state: "23", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "电气技改停机" },
  { id: 68, state: "24", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "电气故障停机" },
  { id: 69, state: "25", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "电网故障停机" },
  { id: 70, state: "26", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 76, stateDesc: "电网检修停机" },
  {
    id: 77,
    state: "5",
    color: "#f02828",
    stateType: "MAIN",
    deviceType: "PVINV",
    parentId: null,
    stateDesc: "故障",
    styleInfo: {
      color: "#f02828",
    },
  },
  { id: 71, state: "27", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 77, stateDesc: "故障停机" },
  {
    id: 78,
    state: "6",
    color: "#ffffff",
    stateType: "MAIN",
    deviceType: "PVINV",
    parentId: null,
    stateDesc: "无通讯",
    styleInfo: {
      color: "#ffffff",
    },
  },
  { id: 72, state: "28", color: "", stateType: "SUB", deviceType: "PVINV", parentId: 78, stateDesc: "无通讯" },
]

export const getStateForType = () => {
  const WT = STATE_TYPE.filter((i) => i.deviceType === "WT")
  const PVINV = STATE_TYPE.filter((i) => i.deviceType === "PVINV")
  const ESPCS = STATE_TYPE.filter((i) => i.deviceType === "ESPCS")
  const res = {
    WT,
    PVINV,
    ESPCS,
  }
  return res
}
