/*
 * @Author: chenmeifeng
 * @Date: 2025-09-22 11:35:31
 * @LastEditors: chenmeifeng
 * @LastEditTime: 2026-01-05 10:37:19
 * @Description:
 */
export const WT_PVINV_SUB_STATE = {
  WT: [
    { name: "电网限功率", state: "2" },
    { name: "主控限功率", state: "3" },
    { name: "手动限功率", state: "4" },
    { name: "结冰限功率", state: "5" },
    { name: "检测维护", state: "12" },
    { name: "定检维护", state: "13" },
    { name: "巡检维护", state: "14" },
    { name: "缺陷维护", state: "15" },
    { name: "技改维护", state: "16" },
    // {name: "预警维护", state: "17"},
    { name: "覆冰", state: "18" },
    { name: "台风", state: "19" },
    { name: "地震", state: "20" },
    { name: "民事原因", state: "21" },
    { name: "新建风机接入", state: "22" },
    { name: "扇区管理停机", state: "23" },
    { name: "电网限功率停机", state: "24" },
    { name: "现货交易停机", state: "25" },
    { name: "其他原因", state: "26" },
    { name: "电气检测停机", state: "27" },
    { name: "电气定检停机", state: "28" },
    { name: "电气巡检停机", state: "29" },
    { name: "电气缺陷停机", state: "30" },
    { name: "电气技改停机", state: "31" },
    { name: "电气故障停机", state: "32" },
    { name: "电网故障停机", state: "33" },
    { name: "电网检修停机", state: "34" },
    { name: "故障检修", state: "35" },
    // {name: "故障停机", state: "36"},
  ],
  PVINV: [
    { name: "电网限功率", state: "2" },
    { name: "主控限功率", state: "3" },
    { name: "检测维护", state: "5" },
    { name: "定检维护", state: "6" },
    { name: "缺陷维护", state: "7" },
    { name: "技改维护", state: "8" },
    // { name: "预警维护", state: "9" },
    { name: "故障维护", state: "10" },
    { name: "积雪", state: "11" },
    { name: "台风", state: "12" },
    { name: "地震", state: "13" },
    { name: "民事原因", state: "14" },
    { name: "新建设备接入", state: "15" },
    { name: "电网限功率停机", state: "16" },
    { name: "现货交易停机", state: "17" },
    { name: "其他原因", state: "18" },
    { name: "电气检测停机", state: "19" },
    { name: "电气定检停机", state: "20" },
    { name: "电气巡检停机", state: "21" },
    { name: "电气缺陷停机", state: "22" },
    { name: "电气技改停机", state: "23" },
    { name: "电气故障停机", state: "24" },
    { name: "电网故障停机", state: "25" },
    { name: "电网检修停机", state: "26" },
  ],
}
export const WT_PVINV_MAIN_STATE = {
  WT: [
    { name: "正常发电", state: "1" },
    { name: "限功率", state: "2" },
    { name: "待机", state: "3" },
    { name: "维护", state: "4" },
    { name: "停机", state: "5" },
    { name: "故障", state: "6" },
    { name: "无通讯", state: "7" },
  ],
  PVINV: [
    { name: "正常发电", state: "1" },
    { name: "限功率", state: "2" },
    { name: "待机", state: "3" },
    { name: "停机", state: "4" },
    { name: "故障", state: "5" },
    { name: "无通讯", state: "6" },
  ],
}
